### ISSUE TITLE
User repositories not backed up

### ISSUE THREAD

**Issue by davidsarkany** [itsTeknas/GitlabBackupUtil#1]
This script only backup groups repositories.

See my solution:
https://github.com/davidsarkany/gitlab-backup-util/blob/master/app.js

**Comment by itsTeknas** [comment]
Your link doesn't work.

**Comment by davidsarkany** [comment]
@itsTeknas 
It's a new link
https://github.com/davidsarkany/gitlab-backup-util/blob/master/app.js

**Comment by itsTeknas** [comment]
I like your usage of nodegit, will use this as a reference and add support for individual repos also later.
